from django.db import models

# Create your models here.
class Moves(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Pokemon(models.Model):
    name = models.CharField(max_length=50)
    entry = models.CharField(max_length=600)
    moves = models.ManyToManyField(Moves)
    slug = models.CharField(max_length=50, blank=True, editable=False,
                        help_text="Unique URL path to access this page. Generated by the system.")
    created = models.DateTimeField(auto_now_add=True,
                        help_text="The date and time this page was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
                        help_text="The date and time this page was updated. Automatically generated when the model updates.")
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        """ Returns a fully-qualified path for a page. """
        path_components = {'slug': self.slug}
        return reverse('pokemon-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a page is created. """
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Pokemon, self).save(*args, **kwargs)